version: '3.3'

services:
  web:
    build: .
    command:  yarn serve
    working_dir: /usr/app
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    ports:
      - '8080:8080'

  proxy:
    image: nginx
    restart: always
    volumes:
      - ./lambda/default.conf:/etc/nginx/conf.d/default.conf
      - ./lambda/api_proxy.conf:/etc/nginx/api_proxy.conf
    ports:
      - '9000:80'

  db:
    image: postgres
    environment:
      POSTGRES_USER: amplio
      POSTGRES_PASSWORD: fooFaBar
      POSTGRES_DB: amplio_db
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  python-deps:
    build:
      context: ./lambda
    volumes:
      - './lambda:/usr/src/app'
      - package:/usr/src/app/package

  lambda-test:
    image: lambci/lambda:python3.8
    command: test_function.lambda_handler
    environment:
      # Funtions with hot reload
      DOCKER_LAMBDA_STAY_OPEN: 1
      DOCKER_LAMBDA_WATCH: 1
    volumes:
      - './lambda:/var/task:ro,delegated'
      - package:/var/task/package
    depends_on:
      - db

  lambda-migration:
    image: lambci/lambda:python3.8
    command: migrations.lambda_handler
    environment:
      # Funtions with hot reload
      DOCKER_LAMBDA_STAY_OPEN: 1
      DOCKER_LAMBDA_WATCH: 1
    volumes:
      - './lambda:/var/task:ro,delegated'
      - package:/var/task/package
    depends_on:
      - db

  lambda-new-program:
    image: lambci/lambda:python3.8
    command: new_program.lambda_handler
    environment:
      # Funtions with hot reload
      DOCKER_LAMBDA_STAY_OPEN: 1
      DOCKER_LAMBDA_WATCH: 1
    volumes:
      - './lambda:/var/task:ro,delegated'
      - package:/var/task/package
    depends_on:
      - db

volumes:
  node_modules:
  postgres-data:
  package:
    driver: local
    driver_opts:
      type: none
      device: $PWD/lambda/package
      o: bind
