version: '3.3'

services:
  web:
    build: .
    command: yarn serve
    working_dir: /usr/app
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    ports:
      - '8080:8080'

  proxy:
    image: openresty/openresty:1.19.3.1-2-buster
    volumes:
      - ./proxy/:/etc/nginx/
    ports:
      - '9000:80'

  db:
    image: postgres:13.0
    environment:
      POSTGRES_USER: amplio
      POSTGRES_PASSWORD: fooFaBar
      POSTGRES_DB: ampliosuite
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  dynamodb:
    image: amazon/dynamodb-local
    # command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    ports:
      - "8008:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

  python-deps:
    build:
      context: ./lambda
    environment:
      PYTHONPATH: "/opt/python/:/usr/src/app/package"
    depends_on:
      - lambda-migration
    volumes:
      - ./lambda/site.py:/var/lang/lib/python3.8/site.py
      - ./lambda:/opt/python

  lambda-migration: &base
    image: lambci/lambda:python3.8
    command: migrations.lambda_handler
    environment:
      # Funtions with hot reload
      DOCKER_LAMBDA_STAY_OPEN: 1
      DOCKER_LAMBDA_WATCH: 1
    volumes:
      - ./lambda/site.py:/var/lang/lib/python3.8/site.py
      - ./lambda:/opt/python:ro,delegated
    depends_on:
      - db

  lambda-programs_index:
    <<: *base
    command: programs_index.lambda_handler

  lambda-program_retrieve:
    <<: *base
    command: program_retrieve.lambda_handler

  lambda-program_create:
    <<: *base
    command: program_create.lambda_handler

  lambda-program_update:
    <<: *base
    command: program_update.lambda_handler

  lambda-program_next_deployment:
    <<: *base
    command: program_next_deployment.lambda_handler

  lambda-project_retrieve:
    <<: *base
    command: project_retrieve.lambda_handler

  lambda-project_create:
    <<: *base
    command: project_create.lambda_handler

  lambda-content_retrieve:
    <<: *base
    command: content_retrieve.lambda_handler

  lambda-content_create:
    <<: *base
    command: content_create.lambda_handler

  lambda-content_update:
    <<: *base
    command: content_update.lambda_handler

  lambda-playlist_create:
    <<: *base
    command: playlist_create.lambda_handler

  # lambda-playlist_delete:
  #   <<: *base
  #   command: playlist_delete.lambda_handler

  lambda-message_create:
    <<: *base
    command: message_create.lambda_handler

  # lambda-message_delete:
  #   <<: *base
  #   command: message_delete.lambda_handler

  lambda-recipient_retrieve:
    <<: *base
    command: recipient_retrieve.lambda_handler

  lambda-recipient_create:
    <<: *base
    command: recipient_create.lambda_handler

  lambda-recipient_update:
    <<: *base
    command: recipient_update.lambda_handler

  lambda-recipient_delete:
    <<: *base
    command: recipient_delete.lambda_handler

  lambda-deployment_retrieve:
    <<: *base
    command: deployment_retrieve.lambda_handler

  lambda-deployment_update:
    <<: *base
    command: deployment_update.lambda_handler

  lambda-deployment_delete:
    <<: *base
    command: deployment_delete.lambda_handler

  lambda-categories_index:
    <<: *base
    command: categories_index.lambda_handler

  lambda-languages_index:
    <<: *base
    command: languages_index.lambda_handler

  lambda-sustainable_developments_index:
    <<: *base
    command: sustainable_developments_index.lambda_handler

  lambda-listening_model_index:
    <<: *base
    command: listening_model_index.lambda_handler

  lambda-roadmap_index:
    <<: *base
    command: roadmap_index.lambda_handler

  lambda-roadmap_update:
    <<: *base
    command: roadmap_update.lambda_handler

  lambda-deploy:
    <<: *base
    command: deploy.lambda_handler

volumes:
  node_modules:
  postgres-data:
  dynamodb_data:
