version: '3.3'

services:
  web:
    build:
      context: ./frontend
    command: yarn serve
    working_dir: /usr/app
    volumes:
      - ./frontend:/usr/app
      - node_modules:/usr/app/node_modules
    ports:
      - '8080:8080'

  proxy:
    image: openresty/openresty:1.19.3.1-2-buster
    volumes:
      - ./proxy/:/etc/nginx/
    ports:
      - '9000:80'

  # db:
  #   image: postgres:13.0
  #   environment:
  #     POSTGRES_USER: amplio
  #     POSTGRES_PASSWORD: fooFaBar
  #     POSTGRES_DB: ampliosuite
  #   volumes:
  #     - 'postgres-data:/var/lib/postgresql/data'

  dynamodb:
    image: amazon/dynamodb-local
    # command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    ports:
      - "8008:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

  python-deps:
    build:
      context: ./lambda
    environment:
      PYTHONPATH: "/opt/python/:/usr/src/app/package"
    volumes:
      - ./lambda/site.py:/var/lang/lib/python3.8/site.py
      - ./lambda:/opt/python
    # depends_on:
    #   - db

  lambda-project_create:  &base
    image: lambci/lambda:python3.8
    command: projects.router.create_project
    environment:
      # Funtions with hot reload
      - DOCKER_LAMBDA_STAY_OPEN=1
      - DOCKER_LAMBDA_WATCH=1
      - DATABASE_URL
    volumes:
      - ./lambda/site.py:/var/lang/lib/python3.8/site.py
      - ./lambda:/opt/python:ro
    # depends_on:
    #   - db

  lambda-project_get:
    <<: *base
    command: projects.router.get_project

  lambda-projects_get_by_user:
    <<: *base
    command: projects.router.get_projects_by_user

  lambda-program_create:
    <<: *base
    command: programs.router.create_program

  lambda-program_get:
    <<: *base
    command: programs.router.get_program

  lambda-program_update:
    <<: *base
    command: programs.router.update_program

  lambda-deployments_create:
    <<: *base
    command: deployments.router.create_deployments

  lambda-deployments_get:
    <<: *base
    command: deployments.router.get_deployments

  lambda-deployments_update:
    <<: *base
    command: deployments.router.update_deployments

  lambda-deployments_delete:
    <<: *base
    command: deployments.router.delete_deployments

  lambda-playlist_create:
    <<: *base
    command: playlists.router.create_playlist

  lambda-playlist_delete:
    <<: *base
    command: playlists.router.delete_playlist

  lambda-playlists_get_multi:
    <<: *base
    command: playlists.router.get_multi_playlists

  lambda-playlists_update_multi:
    <<: *base
    command: playlists.router.update_multi_playlists

  lambda-message_create:
    <<: *base
    command: messages.router.create_message

  lambda-message_delete:
    <<: *base
    command: messages.router.delete_message

  lambda-messages_update_multi:
    <<: *base
    command: messages.router.update_multi_messages

  lambda-recipient_create:
    <<: *base
    command: recipients.router.create_recipient

  lambda-recipient_get:
    <<: *base
    command: recipients.router.get_recipient

  lambda-recipient_update:
    <<: *base
    command: recipients.router.update_recipient

  lambda-recipient_delete:
    <<: *base
    command: recipients.router.delete_recipient

  lambda-recipients_retrieve_by_program:
    <<: *base
    command: recipients.router.get_recipients_by_program

  lambda-deploy:
    <<: *base
    command: deploy.router.lambda_handler

  lambda-roadmap_get:
    <<: *base
    command: roadmaps.router.get_roadmap

  lambda-roadmap_update:
    <<: *base
    command: roadmaps.router.update_roadmap

  lambda-languages_index:
    <<: *base
    command: languages.router.get_languages

  lambda-listening_model_index:
    <<: *base
    command: listening_models.router.get_listening_models

  lambda-supported_categories_index:
    <<: *base
    command: supported_categories.router.get_supported_categories

  lambda-sustainable_developments_index:
    <<: *base
    command: sustainable_developments.router.get_sustainable_developments

  adminer:
    image: adminer
    ports:
      - 8081:8080

volumes:
  node_modules:
  postgres-data:
  dynamodb_data:
