"""Create Deployments

Revision ID: 186bbcef6df2
Revises: 79be0b254bf5
Create Date: 2020-06-25 16:23:10.239841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186bbcef6df2'
down_revision = '79be0b254bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('deployment', sa.String(length=255), nullable=False),
    sa.Column('deploymentname', sa.String(length=255), nullable=True),
    sa.Column('deploymentnumber', sa.Integer(), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.Column('enddate', sa.Date(), nullable=True),
    sa.Column('distribution', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('component', sa.String(), nullable=False),
    sa.UniqueConstraint('project', 'deployment', name='deployments_uniqueness_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deployments')
    # ### end Alembic commands ###
