"""create content table

Revision ID: 37be23fd2712
Revises: d4a994aec9ca
Create Date: 2020-07-13 13:27:54.435668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37be23fd2712'
down_revision = 'd4a994aec9ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('program_code', sa.String(length=255), nullable=False),
    sa.Column('deployment_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('program_code', 'deployment_id'),
    sa.UniqueConstraint('program_code', 'deployment_id', name='content_uniqueness_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    # ### end Alembic commands ###
