"""Create sustainable development goals and targets tables

Revision ID: 58b4f4bb9b23
Revises: 0a4e5bc1d211
Create Date: 2020-08-05 16:00:47.680927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b4f4bb9b23'
down_revision = '0a4e5bc1d211'
branch_labels = None
depends_on = None


def upgrade():
    sd_goals = op.create_table('sustainable_development_goals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=250), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    sd_target = op.create_table('sustainable_development_targets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('parent', sa.Integer(), nullable=True),
        sa.Column('subsection', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=250), nullable=True),
        sa.ForeignKeyConstraint(['parent'], ['sustainable_development_goals.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(sd_goals, [
        { 'id': 1, 'label': 'No Poverty' },
        { 'id': 2, 'label': 'Zero Hunger' },
        { 'id': 3, 'label': 'Good Health and Well-being' },
        { 'id': 4, 'label': 'Quality Education' },
        { 'id': 5, 'label': 'Gender Equality' },
        { 'id': 6, 'label': 'Clean Water and Sanitation' },
        { 'id': 7, 'label': 'Affordable and Clean Energy' },
        { 'id': 8, 'label': 'Decent Work and Economic Growth' },
        { 'id': 9, 'label': 'Industry, Innovation and Infrastructure' },
        { 'id': 10, 'label': 'Reduced Inequality' },
        { 'id': 11, 'label': 'Sustainable Cities and Communities' },
        { 'id': 12, 'label': 'Responsible Consumption and Production' },
        { 'id': 13, 'label': 'Climate Action' },
        { 'id': 14, 'label': 'Life Below Water' },
        { 'id': 15, 'label': 'Life on Land' },
        { 'id': 16, 'label': 'Peace and Justice Strong Institutions' },
        { 'id': 17, 'label': 'Partnerships to achieve the Goal' }
    ])

    op.bulk_insert(sd_target, [
        { 'parent': 1, 'subsection': 1, 'label': "Eradicate extreme poverty"},
        { 'parent': 1, 'subsection': 2, 'label': "Reduce poverty by at least 50%"},
        { 'parent': 1, 'subsection': 3, 'label': "Implement social protection systems"},
        { 'parent': 1, 'subsection': 4, 'label': "Equal rights to ownership, basic services, technology and economic resources"},
        { 'parent': 1, 'subsection': 5, 'label': "Build resilience to environmental, economic and social disasters"},
        { 'parent': 2, 'subsection': 1, 'label': "Universal access to safe and nutritious food"},
        { 'parent': 2, 'subsection': 2, 'label': "End all forms of malnutrition"},
        { 'parent': 2, 'subsection': 3, 'label': "Double the productivity and incomes of small-scale food producers"},
        { 'parent': 2, 'subsection': 4, 'label': "Sustainable food production and resilient agricultural practices"},
        { 'parent': 2, 'subsection': 5, 'label': "Maintain the genetic diversity in food production"},
        { 'parent': 3, 'subsection': 1, 'label': "Reduce maternal mortality"},
        { 'parent': 3, 'subsection': 2, 'label': "End all preventable deaths under 5 years of age"},
        { 'parent': 3, 'subsection': 3, 'label': "Fight communicable diseases"},
        { 'parent': 3, 'subsection': 4, 'label': "Reduce mortality from non-communicable diseases and promote mental health"},
        { 'parent': 3, 'subsection': 5, 'label': "Prevent and treat substance abuse"},
        { 'parent': 3, 'subsection': 6, 'label': "Reduce road injuries and deaths"},
        { 'parent': 3, 'subsection': 7, 'label': "Universal access to sexual and reproductive care, family planning and education"},
        { 'parent': 3, 'subsection': 8, 'label': "Achieve universal health coverage"},
        { 'parent': 3, 'subsection': 9, 'label': "Reduce illnesses and deaths from hazardous chemicals and pollution"},
        { 'parent': 4, 'subsection': 1, 'label': "Free primary and secondary education"},
        { 'parent': 4, 'subsection': 2, 'label': "Equal access to quality pre-primary education"},
        { 'parent': 4, 'subsection': 3, 'label': "Equal access to affordable technical, vocational and higher education"},
        { 'parent': 4, 'subsection': 4, 'label': "Increase the number of people with relevant skills for financial success"},
        { 'parent': 4, 'subsection': 5, 'label': "Eliminate all discrimination in education"},
        { 'parent': 4, 'subsection': 6, 'label': "Universal literacy and numeracy"},
        { 'parent': 4, 'subsection': 7, 'label': "Education for sustainable development and global citizenship"},
        { 'parent': 5, 'subsection': 1, 'label': "End discrimination against women and girls"},
        { 'parent': 5, 'subsection': 2, 'label': "End all violence against and exploitation of women and girls"},
        { 'parent': 5, 'subsection': 3, 'label': "Eliminate forced marriages and genital mutilation"},
        { 'parent': 5, 'subsection': 4, 'label': "Value unpaid care and promote shared domestic responsibilities"},
        { 'parent': 5, 'subsection': 5, 'label': "Ensure full participation in leadership and decision-making"},
        { 'parent': 5, 'subsection': 6, 'label': "Universal access to reproductive rights and health"},
        { 'parent': 6, 'subsection': 1, 'label': "Safe and affordable drinking water"},
        { 'parent': 6, 'subsection': 2, 'label': "End open defecation and provide access to sanitation and hygiene"},
        { 'parent': 6, 'subsection': 3, 'label': "Improve water quality, wastewater treatment and safe reuse"},
        { 'parent': 6, 'subsection': 4, 'label': "Increase water use efficiency and ensure freshwater supplies"},
        { 'parent': 6, 'subsection': 5, 'label': "Implement integrated water resources management"},
        { 'parent': 6, 'subsection': 6, 'label': "Protect and restore water-related ecosystems"},
        { 'parent': 7, 'subsection': 1, 'label': "Universal access to modern energy"},
        { 'parent': 7, 'subsection': 2, 'label': "Increase global percentage of renewable energy"},
        { 'parent': 7, 'subsection': 3, 'label': "Double the improvement in energy efficiency"},
        { 'parent': 8, 'subsection': 1, 'label': "Sustainable Economic Growth"},
        { 'parent': 8, 'subsection': 2, 'label': "Diversify, innovate and upgrade for economic productivity"},
        { 'parent': 8, 'subsection': 3, 'label': "Promote policies to support job creation and growing enterprises"},
        { 'parent': 8, 'subsection': 4, 'label': "Improve resource efficiency in consumption and production"},
        { 'parent': 8, 'subsection': 5, 'label': "Full employment and decent work with equal pay"},
        { 'parent': 8, 'subsection': 6, 'label': "Promote youth employment, education and training"},
        { 'parent': 8, 'subsection': 7, 'label': "End modern slavery, trafficking, and child labour"},
        { 'parent': 8, 'subsection': 8, 'label': "Protect labour rights and promote safe working environments"},
        { 'parent': 8, 'subsection': 9, 'label': "Promote beneficial and sustainable tourism"},
        { 'parent': 8, 'subsection': 10, 'label': "Universal access to banking, insurance and financial services"},
        { 'parent': 9, 'subsection': 1, 'label': "Develop sustainable, resilient and inclusive infrastructures"},
        { 'parent': 9, 'subsection': 2, 'label': "Promote inclusive and sustainable industrialization"},
        { 'parent': 9, 'subsection': 3, 'label': "Increase access to financial services and markets"},
        { 'parent': 9, 'subsection': 4, 'label': "Upgrade all industries and infrastructures for sustainability"},
        { 'parent': 9, 'subsection': 5, 'label': "Enhance research and upgrade industrial technologies"},
        { 'parent': 10, 'subsection': 1, 'label': "Reduce income inequalities"},
        { 'parent': 10, 'subsection': 2, 'label': "Promote universal social, economic and political inclusion"},
        { 'parent': 10, 'subsection': 3, 'label': "Ensure equal opportunities and end discrimination"},
        { 'parent': 10, 'subsection': 4, 'label': "Adopt fiscal and social policies that promotes equality"},
        { 'parent': 10, 'subsection': 5, 'label': "Improved regulation of global financial markets and institutions"},
        { 'parent': 10, 'subsection': 6, 'label': "Enhanced representation for developing countries in financial institutions"},
        { 'parent': 10, 'subsection': 7, 'label': "Responsible and well-managed migration policies"},
        { 'parent': 11, 'subsection': 1, 'label': "Safe and affordable housing"},
        { 'parent': 11, 'subsection': 2, 'label': "Affordable and sustainable transport systems"},
        { 'parent': 11, 'subsection': 3, 'label': "Inclusive and sustainable urbanization"},
        { 'parent': 11, 'subsection': 4, 'label': "Protect the world's cultural and natural heritage"},
        { 'parent': 11, 'subsection': 5, 'label': "Reduce the adverse effects of natural disasters"},
        { 'parent': 11, 'subsection': 6, 'label': "Reduce the environmental impacts of cities"},
        { 'parent': 11, 'subsection': 7, 'label': "Provide access to safe and inclusive green and public spaces"},
        { 'parent': 12, 'subsection': 1, 'label': "Implement the 10-year sustainable consumption and production framework"},
        { 'parent': 12, 'subsection': 2, 'label': "Sustainable management and use of natural resources"},
        { 'parent': 12, 'subsection': 3, 'label': "Halve global per capita food waste"},
        { 'parent': 12, 'subsection': 4, 'label': "Responsible management of chemicals and waste"},
        { 'parent': 12, 'subsection': 5, 'label': "Substantially reduce waste generation"},
        { 'parent': 12, 'subsection': 6, 'label': "Encourage companies to adopt sustainable practices and sustainability reporting"},
        { 'parent': 12, 'subsection': 7, 'label': "Promote sustainable public procurement practices"},
        { 'parent': 12, 'subsection': 8, 'label': "Promote universal understanding of sustainable lifestyles"},
        { 'parent': 13, 'subsection': 1, 'label': "Strengthen resilience and adaptive capacity to climate-related disasters"},
        { 'parent': 13, 'subsection': 2, 'label': "Integrate climate change measures into policy and planning"},
        { 'parent': 13, 'subsection': 3, 'label': "Build knowledge and capacity to meet climate change"},
        { 'parent': 14, 'subsection': 1, 'label': "Reduce marine pollution"},
        { 'parent': 14, 'subsection': 2, 'label': "Protect and restore ecosystems"},
        { 'parent': 14, 'subsection': 3, 'label': "Reduce ocean acidification"},
        { 'parent': 14, 'subsection': 4, 'label': "Sustainable fishing"},
        { 'parent': 14, 'subsection': 5, 'label': "Conserve coastal and marine areas"},
        { 'parent': 14, 'subsection': 6, 'label': "End subsidies contributing to overfishing"},
        { 'parent': 14, 'subsection': 7, 'label': "Increase the economic benefits from sustainable use of marine resources"},
        { 'parent': 15, 'subsection': 1, 'label': "Conserve and restore terrestrial and freshwater ecosystems"},
        { 'parent': 15, 'subsection': 2, 'label': "End deforestation and restore degraded forests"},
        { 'parent': 15, 'subsection': 3, 'label': "End desertification and restore degraded land"},
        { 'parent': 15, 'subsection': 4, 'label': "Ensure conservation of mountain ecosystems"},
        { 'parent': 15, 'subsection': 5, 'label': "Protect biodiversity and natural habitats"},
        { 'parent': 15, 'subsection': 6, 'label': "Protect access to genetic resources and fair sharing of the benefits"},
        { 'parent': 15, 'subsection': 7, 'label': "Eliminate poaching and trafficking of protected species"},
        { 'parent': 15, 'subsection': 8, 'label': "Prevent invasive alien species on land and in water ecosystems"},
        { 'parent': 15, 'subsection': 9, 'label': "Integrate ecosystem and biodiversity in governmental planning"},
        { 'parent': 16, 'subsection': 1, 'label': "Reduce violence everywhere"},
        { 'parent': 16, 'subsection': 2, 'label': "Protect children from abuse, exploitation, trafficking and violence"},
        { 'parent': 16, 'subsection': 3, 'label': "Promote the rule of law and ensure equal access to justice"},
        { 'parent': 16, 'subsection': 4, 'label': "Combat organized crime and illicit financial and arms flows"},
        { 'parent': 16, 'subsection': 5, 'label': "Substantially reduce corruption and bribery"},
        { 'parent': 16, 'subsection': 6, 'label': "Develop effective, accountable and transparent institutions"},
        { 'parent': 16, 'subsection': 7, 'label': "Ensure responsive, inclusive and representative decision-making"},
        { 'parent': 16, 'subsection': 8, 'label': "Strengthen the participation in global governance"},
        { 'parent': 16, 'subsection': 9, 'label': "Provide universal legal identity"},
        { 'parent': 16, 'subsection': 10, 'label': "Ensure public access to information and protect fundamental freedoms"},
        { 'parent': 17, 'subsection': 1, 'label': "Mobilize resources to improve domestic revenue collection"},
        { 'parent': 17, 'subsection': 2, 'label': "Implement all development assistance commitments"},
        { 'parent': 17, 'subsection': 3, 'label': "Mobilize financial resources for developing countries"},
        { 'parent': 17, 'subsection': 4, 'label': "Assist developing countries in attaining debt sustainability"},
        { 'parent': 17, 'subsection': 5, 'label': "Invest in least-developed countries"},
        { 'parent': 17, 'subsection': 6, 'label': "Knowledge sharing and cooperation for access to science, technology and innovation"},
        { 'parent': 17, 'subsection': 7, 'label': "Promote sustainable technologies to developing countries"},
        { 'parent': 17, 'subsection': 8, 'label': "Strengthen the science, technology and innovation capacity for least-developed countries"},
        { 'parent': 17, 'subsection': 9, 'label': "Enhanced SDG capacity in developing countries"},
        { 'parent': 17, 'subsection': 10, 'label': "Promote a universal trading system under the WTO"},
        { 'parent': 17, 'subsection': 11, 'label': "Increase the exports of developing countries"},
        { 'parent': 17, 'subsection': 12, 'label': "Remove trade barriers for least-developed countries"},
        { 'parent': 17, 'subsection': 13, 'label': "Enhance global macroeconomic stability"},
        { 'parent': 17, 'subsection': 14, 'label': "Enhance policy coherence for sustainable development"},
        { 'parent': 17, 'subsection': 15, 'label': "Respect national leadership to implement policies for the sustainable development goals"},
        { 'parent': 17, 'subsection': 16, 'label': "Enhance the global partnership for sustainable development"},
        { 'parent': 17, 'subsection': 17, 'label': "Encourage effective partnerships"},
        { 'parent': 17, 'subsection': 18, 'label': "Enhance availability of reliable data"},
        { 'parent': 17, 'subsection': 19, 'label': "Further develop measurements of progress"},
    ])


def downgrade():
    op.drop_table('sustainable_development_targets')
    op.drop_table('sustainable_development_goals')
