"""Add project code to programs

Revision ID: 6315eef7a103
Revises: 186bbcef6df2
Create Date: 2020-06-25 18:29:20.869647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6315eef7a103'
down_revision = '186bbcef6df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('project', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'project')
    # ### end Alembic commands ###
