"""Add playlist and messages

Revision ID: 6637cbcbd80b
Revises: 10b0848a46f0
Create Date: 2021-01-18 05:34:24.712509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '6637cbcbd80b'
down_revision = '10b0848a46f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')

    op.create_table('playlists',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('program_code', sa.String(), nullable=False),
        sa.Column('deployment_id', sa.String(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('audience', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['program_code', 'deployment_id'],
            ['deployments.project', 'deployments.deployment'],
            name='playlist_program_code_fkey',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', 'program_code'),
        sa.UniqueConstraint(
            'program_code',
            'deployment_id',
            'position',
            name='playlist_uniqueness_key',
        )
    )
    op.create_index(op.f('ix_playlists_id'), 'playlists', ['id'], unique=False)
    op.create_index(op.f('ix_playlists_program_code'), 'playlists', ['program_code'], unique=False)

    op.create_table('messages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('program_code', sa.String(), nullable=False),
        sa.Column('playlist_id', sa.Integer(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('format', sa.String(), nullable=True),
        sa.Column('default_category_id', sa.String(), nullable=True),
        sa.Column('variant', sa.String(), nullable=True),
        sa.Column('sdg_goal_id', sa.Integer(), nullable=True),
        sa.Column('sdg_target_id', sa.Integer(), nullable=True),
        sa.Column('key_point', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['program_code', 'playlist_id'],
            ['playlists.program_code', 'playlists.id'],
            name='message_program_code_fkey',
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['default_category_id'],
            ['supportedcategories.categorycode'],
            name='message_category_fkey',
        ),
        sa.ForeignKeyConstraint(
            ['sdg_goal_id'],
            ['sustainable_development_goals.section'],
            name='message_sdg_goal_fkey'
        ),
        sa.ForeignKeyConstraint(
            ['sdg_goal_id', 'sdg_target_id'],
            [
                'sustainable_development_targets.goal_id',
                'sustainable_development_targets.subsection',
            ],
            name='message_sdg_target_fkey'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'program_code',
            'playlist_id',
            'position',
            name='message_uniqueness_key'
        )
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_program_code'), 'messages', ['program_code'], unique=False)

    op.create_table('message_languages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message_id', sa.Integer(), nullable=False),
        sa.Column('language_code', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['language_code'], ['supportedlanguages.languagecode'], ),
        sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_languages_id'), 'message_languages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_languages_id'), table_name='message_languages')
    op.drop_table('message_languages')

    op.drop_index(op.f('ix_messages_program_code'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')

    op.drop_index(op.f('ix_playlists_program_code'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_id'), table_name='playlists')
    op.drop_table('playlists')

    op.create_table('content',
        sa.Column('projectcode', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('deployment', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['projectcode', 'deployment'], ['deployments.project', 'deployments.deployment'], name='content_program_code_fkey'),
        sa.UniqueConstraint('projectcode', 'deployment', name='content_uniqueness_key')
    )
    # ### end Alembic commands ###
