"""Create Projects

Revision ID: 79be0b254bf5
Revises: 039c39497278
Create Date: 2020-06-25 16:10:08.622668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79be0b254bf5'
down_revision = '039c39497278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('projectcode', sa.String(length=255), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.UniqueConstraint('projectcode', name='projects_uniqueness_key')
    )
    op.create_index(op.f('ix_projects_projectcode'), 'projects', ['projectcode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_projectcode'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
