"""Add project name column to the Project table

Revision ID: 82a6552ae136
Revises: 8331cd65623e
Create Date: 2020-07-20 13:35:15.234784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82a6552ae136'
down_revision = '8331cd65623e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'name')
    # ### end Alembic commands ###
