"""Remove program.feedback_frequency_other column

Revision ID: b33dbd8685c6
Revises: 6637cbcbd80b
Create Date: 2021-01-27 18:36:26.329967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33dbd8685c6'
down_revision = '6637cbcbd80b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('programs', 'feedback_frequency_other')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('feedback_frequency_other', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
