"""add roadmap table

Revision ID: c0b39e045fba
Revises: 3d3e7597700e
Create Date: 2020-08-18 20:50:41.348090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b39e045fba'
down_revision = '3d3e7597700e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('program_code', sa.String(), nullable=False),
        sa.Column('completed', sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('program_code', name='roadmap_program_code_uniqueness_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roadmap')
    # ### end Alembic commands ###
