"""Message langs ondelete cascade

Revision ID: d41294df6dc7
Revises: b33dbd8685c6
Create Date: 2021-03-18 18:23:34.286609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41294df6dc7'
down_revision = 'b33dbd8685c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('message_languages_language_code_fkey', 'message_languages', type_='foreignkey')
    op.create_foreign_key(None, 'message_languages', 'supportedlanguages', ['language_code'], ['languagecode'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message_languages', type_='foreignkey')
    op.create_foreign_key('message_languages_language_code_fkey', 'message_languages', 'supportedlanguages', ['language_code'], ['languagecode'])
    # ### end Alembic commands ###
