"""Add project code to programs

Revision ID: d4a994aec9ca
Revises: 186bbcef6df2
Create Date: 2020-06-25 19:17:15.300675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a994aec9ca'
down_revision = '186bbcef6df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('project', sa.String(length=255), nullable=False))
    op.create_unique_constraint('programs_uniqueness_key', 'programs', ['project'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('programs_uniqueness_key', 'programs', type_='unique')
    op.drop_column('programs', 'project')
    # ### end Alembic commands ###
