map $original_request $lambda {
  'GET /program HTTP/1.1'  http://lambda-program_retrieve:9001/2015-03-31/functions/program_retrieve/invocations;
  'POST /program HTTP/1.1' http://lambda-program_create:9001/2015-03-31/functions/program_create/invocations;
  'PUT /program HTTP/1.1' http://lambda-program_update:9001/2015-03-31/functions/program_update/invocations;

  'GET /deployment HTTP/1.1' http://lambda-deployment_retrieve:9001/2015-03-31/functions/deployment_retrieve/invocations;
  # 'POST /deployment HTTP/1.1'
  'PUT /deployment HTTP/1.1' http://lambda-deployment_update:9001/2015-03-31/functions/deployment_update/invocations;
  'DELETE /deployment HTTP/1.1' http://lambda-deployment_delete:9001/2015-03-31/functions/deployment_delete/invocations;

  'GET /content HTTP/1.1'  http://lambda-content_retrieve:9001/2015-03-31/functions/content_retrieve/invocations;
  'POST /content HTTP/1.1' http://lambda-content_create:9001/2015-03-31/functions/content_create/invocations;
  'PUT /content HTTP/1.1'  http://lambda-content_update:9001/2015-03-31/functions/content_update/invocations;
  # 'DELETE /content HTTP/1.1'
}

server {
  listen       80;
  server_name  localhost;

  set $original_request $request;

  location /migrations {
    proxy_pass http://lambda-migration:9001/2015-03-31/functions/db_migrations/invocations;
  }

  location /programs {
    include /etc/nginx/api_proxy.conf;
    proxy_pass http://lambda-programs_index:9001/2015-03-31/functions/programs_index/invocations;
  }

  location /program {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;

    proxy_pass $lambda;
  }

  location /program_next_deployment {
    include /etc/nginx/api_proxy.conf;
    proxy_pass http://lambda-program_next_deployment:9001/2015-03-31/functions/program_next_deployment/invocations;
  }

  location /deployment {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;

    proxy_pass $lambda;
  }

  location /content {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;

    proxy_pass $lambda;
  }


  # FIXME: Remove this locations
  location /program_retrieve {
    proxy_pass http://lambda-program_retrieve:9001/2015-03-31/functions/program_retrieve/invocations;
  }
  location /program_create {
    proxy_pass http://lambda-program_create:9001/2015-03-31/functions/program_create/invocations;
  }
  location /program_update {
    proxy_pass http://lambda-program_update:9001/2015-03-31/functions/program_update/invocations;
  }

  location /deployment_retrieve {
    proxy_pass http://lambda-deployment_retrieve:9001/2015-03-31/functions/deployment_retrieve/invocations;
  }
  location /deployment_update {
    proxy_pass http://lambda-deployment_update:9001/2015-03-31/functions/deployment_update/invocations;
  }
  location /deployment_delete {
    proxy_pass http://lambda-deployment_delete:9001/2015-03-31/functions/deployment_delete/invocations;
  }

  location /content_retrieve {
    proxy_pass http://lambda-content_retrieve:9001/2015-03-31/functions/content_retrieve/invocations;
  }
  location /content_create {
    proxy_pass http://lambda-content_create:9001/2015-03-31/functions/content_create/invocations;
  }
  location /content_update {
    proxy_pass http://lambda-content_update:9001/2015-03-31/functions/content_update/invocations;
  }
}
