map $original_request $lambda {
  'GET /programs HTTP/1.1' lambda-projects_get_by_user;

  'GET /program HTTP/1.1'  lambda-program_get;
  'POST /program HTTP/1.1' lambda-program_create;
  'PUT /program HTTP/1.1' lambda-program_update;

  'POST /deployments HTTP/1.1' lambda-deployments_create;
  'GET /deployments HTTP/1.1' lambda-deployments_get;
  'PUT /deployments HTTP/1.1' lambda-deployments_update;
  'DELETE /deployments HTTP/1.1' lambda-deployments_delete;

  'POST /playlist HTTP/1.1' lambda-playlist_create;
  'DELETE /playlist HTTP/1.1' lambda-playlist_delete;
  'GET /playlist HTTP/1.1'  lambda-playlists_get_multi;
  'PUT /playlist HTTP/1.1' lambda-playlists_update_multi;

  'POST /message HTTP/1.1' lambda-message_create;
  'PUT /message HTTP/1.1' lambda-messages_update_multi;
  'DELETE /message HTTP/1.1' lambda-message_delete;

  'GET /recipient HTTP/1.1' lambda-recipient_get;
  'POST /recipient HTTP/1.1' lambda-recipient_create;
  'PUT /recipient HTTP/1.1' lambda-recipient_update;
  'DELETE /recipient HTTP/1.1' lambda-recipient_delete;
  'GET /recipients HTTP/1.1' lambda-recipients_retrieve_by_program;

  'GET /roadmap HTTP/1.1'  lambda-roadmap_get;
  'PUT /roadmap HTTP/1.1'  lambda-roadmap_update;

  'GET /categories HTTP/1.1' lambda-supported_categories_index;
  'GET /languages HTTP/1.1' lambda-languages_index;
  'GET /listening-models HTTP/1.1' lambda-listening_model_index;
  'GET /sustainable-developments HTTP/1.1' lambda-sustainable_developments_index;
}

lua_package_path "/etc/nginx/lua/?.lua;;";

server {
  listen       80;
  server_name  localhost;

  set $original_request $request;

  location /programs {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /program {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /deployments {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /playlist {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /message {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /recipient {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /recipients {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /languages {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /categories {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /listening-models {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /sustainable-developments {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /deploy {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }

  location /roadmap {
    include /etc/nginx/api_proxy.conf;
    rewrite_by_lua_file /etc/nginx/rewrite_method.lua;
  }
}
