server {
  listen       80;
  server_name  localhost;

  location /migrations {
    include /etc/nginx/api_proxy.conf;
    proxy_pass http://lambda-migration:9001/2015-03-31/functions/db_migrations/invocations;
  }

  location /program_create {
    include /etc/nginx/api_proxy.conf;
    proxy_pass http://lambda-program_create:9001/2015-03-31/functions/program_create/invocations;
  }

  location /program_retrieve {
    include /etc/nginx/api_proxy.conf;
    proxy_pass http://lambda-program_retrieve:9001/2015-03-31/functions/program_retrieve/invocations;
  }

  location /programs_index {
    include /etc/nginx/api_proxy.conf;
    proxy_pass http://lambda-programs_index:9001/2015-03-31/functions/programs_index/invocations;
  }

  location /project_create {
    include /etc/nginx/api_proxy.conf;
    proxy_pass http://lambda-project_create:9001/2015-03-31/functions/project_create/invocations;
  }

  location /project_retrieve {
    include /etc/nginx/api_proxy.conf;
    proxy_pass http://lambda-project_retrieve:9001/2015-03-31/functions/project_retrieve/invocations;
  }
}
