server {
  listen       80;
  server_name  localhost;

  location /test {
      proxy_pass http://lambda-test:9001/2015-03-31/functions/test_function/invocations;
  }

  location /migrations {
      proxy_pass http://lambda-migration:9001/2015-03-31/functions/db_migrations/invocations;
  }

  location /new_program {
      proxy_pass http://lambda-new-program:9001/2015-03-31/functions/new_program/invocations;
  }
}
