server {
  listen       80;
  server_name  localhost;

  location /migrations {
      include /etc/nginx/api_proxy.conf;
      proxy_pass http://lambda-migration:9001/2015-03-31/functions/db_migrations/invocations;
  }

  location /new_program {
      include /etc/nginx/api_proxy.conf;
      proxy_pass http://lambda-new-program:9001/2015-03-31/functions/new_program/invocations;
  }
}
